### ISSUE TITLE
Currency Augmentable expecting float but may receive null

### ISSUE THREAD

**Issue by doefom** [doefom/currency-fieldtype#7]
### Description

The Currency class expects a `float` type for the `$value` parameter but in some scenarios `null` may be passed in which causes a type error.

```php
class Currency implements Augmentable
{
   
    ...

    public function __construct(float $value, array $config)
    {
        $this->value = $value;
        $this->config = $config;
    }

    ...

}
```

### Expected Behavior

The constructor should be able to handle `null` values for `$value` without causing any type errors. Perhaps defaulting to `0.0` or providing an alternative solution to handle such cases.

### Steps to Reproduce

Add the currency fieldtype to a blueprint and save the corresponding entry with an empty value for the field. When augmented (e.g. in an Antlers template) the type error is thrown.

### Potential Solution

Consider allowing `$value` to accept both `float` and `null`, and default to `0.0` (or another reasonable default) if `null` is passed.

```php
public function __construct(?float $value, array $config)
{
    $this->value = $value ?? 0.0;
    $this->config = $config;
}
```

Ensure that other logic and augmentable fields can handle the new behavior.

**Comment by caseydwyer** [comment]
Good catch, here. My initial thought: might want to avoid "forcing" a zero into `value` like this, since there are instances where an application might need to differentiate between null and zero values. Eg, an event system where the events have a ticket price that can potentially be free ($0) and could _**also**_ have a null/empty value (ie, the price hasn't been set/published yet). Front end would probably want/need to know when the price is just null (ie, pending), instead of an entered zero. Could also leverage new `default_value` config, to help set this to zero, if that's what an application calls for.

Submitting a PR here in a second, but feel free to push back if you think my approach is whack. 🙂
